### ISSUE TITLE
Debian 10 - Buster : Support of Kamailio-HA

### ISSUE THREAD

**Issue by yboujraf** [ghrst/Kamailio-HA#5]
Dear,

I got your reference from Mr Daniel-Constantin Mierla.

I was looking for a kamailio failover setup running on Debian 10 Buster & kamailio 5.3 (without docker at this stage) :

- one domain name : sip.secure.com pointing my public ip address.
- two kamailio servers pointing same database content (user, whitelist, ...) no asterisk or pbx and/or Cluster.
Kamailio is used Only for signaling (users, whitelist & rtpproxy), to protect AoiP SIP Codec.

Monitoring service : identify who is the kamailio server online, offline and the ability to force all the SIP/RTP/MANAGEMENT connection from Kamailio Srv1 to Kamailio Srv2 and vice-versa ?

Questions : 

- Do you have any diagram how it works ?
+ A two node Active-Passive Kamailio Cluster with a local RTPProxy instance
+ A two node Active-Passive Kamailio Cluster with a cluster of RTPProxy servers

- What the advantage of the two solutions you are proposing ?

- RTPENGINE : 

We would like to use RTPENGINE to record audio on file (Mix of caller and callee or seperated)
+ Is it supported or could modify easily script ?

Best Regards,
Youssef

**Comment by ghrst** [comment]
Hi,

1. Fortunately, your architecture can be implemented using Ansible scripts in this repository. However, to make it work on Debian Buster (I tested it on Debian Stretch), you might need to change a few things

2. This repository uses Corosync, and Pacemaker, which are old, stable, and very well-documented. Corosync provides a heart-beat mechanism to identify nodes in a cluster. On top of this layer Pacemaker can understand your services, e.g VirtualIP, Kamailio, etc. In order to understand how things work you should refer to Pacemaker's documentation at [https://clusterlabs.org/](https://clusterlabs.org/). There is also a book about this topic named [Pro Linux High Availability Clustering](https://www.amazon.com/Pro-Linux-High-Availability-Clustering/dp/1484200802). However, I think the documentation is good enough.

3. If you install a local RTPProxy(or equivalently RTPEngine) instance, then it will become a SPoF. Both by it's capacity to handle concurrent calls, and by stopping. Using a cluster of RTPProxy instances you increase the availability, and capacity of your service.

4. Notice that this ansible repository only sets-up, and installs Kamailio, and RTPProxy. You can record media, but for recording you should refer to RTPEngine's documentation.

**Comment by yboujraf** [comment]
Thanks dear for your quick answer.

Will install your script and let you know.

And what about ipv6. Is it supported ?

Best Regards,
Youssef

**Comment by ghrst** [comment]
As far as I know yes.

**Comment by yboujraf** [comment]
Hi Dear @ghrst 

I hope you are well.

Since our last exchange, did you find any time to update the script for latest kamailio & rtpengine with debian 11 ?

Best Regards
